[tool.poetry]
name = "dzieko"
version = "0.1.0"
description = ""
authors = ["Dawid Stefański"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
